# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/generator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/generator.proto\x12\tgenerator\" \n\x0ePredictRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1c\n\x0cPredictReply\x12\x0c\n\x04urls\x18\x01 \x03(\t2S\n\x10GeneratorService\x12?\n\x07Predict\x12\x19.generator.PredictRequest\x1a\x17.generator.PredictReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.generator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTREQUEST._serialized_start=36
  _PREDICTREQUEST._serialized_end=68
  _PREDICTREPLY._serialized_start=70
  _PREDICTREPLY._serialized_end=98
  _GENERATORSERVICE._serialized_start=100
  _GENERATORSERVICE._serialized_end=183
# @@protoc_insertion_point(module_scope)
