# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/generator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/generator.proto\x12\tgenerator\" \n\x0ePredictRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1f\n\x0fPredictResponse\x12\x0c\n\x04urls\x18\x01 \x03(\t2V\n\x10GeneratorService\x12\x42\n\x07Predict\x12\x19.generator.PredictRequest\x1a\x1a.generator.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.generator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PREDICTREQUEST']._serialized_start=36
  _globals['_PREDICTREQUEST']._serialized_end=68
  _globals['_PREDICTRESPONSE']._serialized_start=70
  _globals['_PREDICTRESPONSE']._serialized_end=101
  _globals['_GENERATORSERVICE']._serialized_start=103
  _globals['_GENERATORSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
